# Commands to start on workspace startup
tasks:
  - init: dotnet restore
    command: dotnet build
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview
image: gitpod/workspace-dotnet